/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.administrador;

import controller.PagesController;
import dao.FuncionarioDao;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author Italo
 */
public class Cadastrar_funcionario extends javax.swing.JFrame {

    public static PagesController controller = new PagesController();
    public static Funcionario funcionario = new Funcionario();
    public static FuncionarioDao funcionariodao = new FuncionarioDao();

    /**
     * Creates new form Cadastrar_funcionario
     */
    public Cadastrar_funcionario() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        img_user = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        input_nome = new javax.swing.JTextField();
        label_sobrenome = new javax.swing.JLabel();
        input_sobrenome = new javax.swing.JTextField();
        label_cpf = new javax.swing.JLabel();
        input_cpf = new javax.swing.JFormattedTextField();
        label_telefone = new javax.swing.JLabel();
        input_telefone = new javax.swing.JFormattedTextField();
        label_cargo = new javax.swing.JLabel();
        select_cargo = new javax.swing.JComboBox<>();
        label_especialide = new javax.swing.JLabel();
        select_especialidade = new javax.swing.JComboBox<>();
        label_adm = new javax.swing.JLabel();
        select_adm = new javax.swing.JComboBox<>();
        label_senha = new javax.swing.JLabel();
        input_senha = new javax.swing.JPasswordField();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(14, 118, 196));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de funcionário");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        img_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user.png"))); // NOI18N

        label_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nome.setText("Nome");

        label_sobrenome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_sobrenome.setText("Sobrenome");

        label_cpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_cpf.setText("CPF");

        try {
            input_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        label_telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_telefone.setText("Telefone");

        try {
            input_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        label_cargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_cargo.setText("Cargo");

        select_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Júnior", "Pleno", "Sênior" }));

        label_especialide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_especialide.setText("Especialidade");

        select_especialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Comercial", "Edifício", "Residencial" }));

        label_adm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_adm.setText("Este usuário é administrador?");

        select_adm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Sim", "Não" }));
        select_adm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_admItemStateChanged(evt);
            }
        });

        label_senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_senha.setText("Senha para o usuário");

        btn_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/ok.png"))); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(img_user))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_nome)
                .addGap(158, 158, 158)
                .addComponent(label_sobrenome)
                .addGap(123, 123, 123)
                .addComponent(label_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(input_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(input_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_telefone)
                .addGap(139, 139, 139)
                .addComponent(label_cargo)
                .addGap(160, 160, 160)
                .addComponent(label_especialide))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(select_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(label_adm)
                                .addGap(6, 6, 6))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(label_senha)
                                .addGap(8, 8, 8)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(input_senha)
                            .addComponent(select_adm, 0, 150, Short.MAX_VALUE))))
                .addGap(47, 47, 47)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar))
                    .addComponent(select_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(img_user)
                .addGap(12, 12, 12)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nome)
                    .addComponent(label_sobrenome)
                    .addComponent(label_cpf))
                .addGap(6, 6, 6)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_telefone)
                    .addComponent(label_cargo)
                    .addComponent(label_especialide))
                .addGap(6, 6, 6)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(label_adm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_senha))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(select_adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cancelar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        controller.fechaTelaInterna(this);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        label_senha.setVisible(false);
        input_senha.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void select_admItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_admItemStateChanged
        if (evt.getStateChange() == 2) {
            if (select_adm.getSelectedItem().toString().equals("Sim")) {
                label_senha.setVisible(true);
                input_senha.setVisible(true);

                return;
            }

            if (select_adm.getSelectedItem().toString().equals("Não")) {
                label_senha.setVisible(false);
                input_senha.setVisible(false);

                return;
            }
        }
    }//GEN-LAST:event_select_admItemStateChanged

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed

        String adm = String.valueOf(select_adm.getSelectedItem());
        int ADM = 0;

        if (adm.equals("Sim")) {
            ADM = 1;
        } else if (adm.equals("Não")) {
            ADM = 0;
        }

        try {

            funcionario.setAdmin(ADM);
            funcionario.setNome(input_nome.getText() + " " + input_sobrenome.getText());
            funcionario.setCpf(input_cpf.getText());
            funcionario.setCargo(select_cargo.getSelectedItem().toString());
            funcionario.setEspecialidade(select_especialidade.getSelectedItem().toString());
            funcionario.setTelefone(input_telefone.getText());
            funcionario.setSenha(input_senha.getText());

            funcionariodao.cadastrarFuncionario(funcionario);

            JOptionPane.showMessageDialog(
                    null,
                    "Funcionário cadastrado com sucesso!",
                    "Cadastro realizado",
                    JOptionPane.INFORMATION_MESSAGE);
           
            input_nome.setText("");
            input_sobrenome.setText("");
            input_cpf.setText("");
            select_cargo.setSelectedItem("-- Selecione --");
            select_especialidade.setSelectedItem("-- Selecione --");
            input_telefone.setText("");
            input_senha.setText("");
            select_adm.setSelectedItem("-- Selecione --");
            

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao tentar cadastrar funcionário!",
                    "Cadastro negado",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel img_user;
    private javax.swing.JFormattedTextField input_cpf;
    private javax.swing.JTextField input_nome;
    private javax.swing.JPasswordField input_senha;
    private javax.swing.JTextField input_sobrenome;
    private javax.swing.JFormattedTextField input_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_adm;
    private javax.swing.JLabel label_cargo;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_especialide;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_sobrenome;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JComboBox<String> select_adm;
    private javax.swing.JComboBox<String> select_cargo;
    private javax.swing.JComboBox<String> select_especialidade;
    // End of variables declaration//GEN-END:variables
}
