/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.administrador;

import model.Funcionario;
import dao.FuncionarioDao;
import controller.PagesController;
import javax.swing.table.DefaultTableModel;
import model.Servico;
import views.Login;
import static views.administrador.Designar_funcionario.servicodao;
import static views.funcionario.Home.fdao;

/**
 *
 * @author Italo
 */
public class Home_adm extends javax.swing.JFrame {
    
    FuncionarioDao funcionariodao = new FuncionarioDao();
    Funcionario funcionario = new Funcionario();
    PagesController controller = new PagesController();
    

    /**
     * Creates new form Home_adm
     */
    public Home_adm() {
        setUndecorated(true);
        initComponents();
        
        rp_logado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        label_nomeUsuario = new javax.swing.JLabel();
        img_cadastrarFuncionario = new javax.swing.JLabel();
        btn_cadastrarFuncionario = new javax.swing.JButton();
        img_editarFuncionario = new javax.swing.JLabel();
        btn_editarFuncionario = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        label_funcionario = new javax.swing.JLabel();
        img_excluirFuncionario = new javax.swing.JLabel();
        btn_excluirFuncionario = new javax.swing.JButton();
        img_pesquisarFuncionario = new javax.swing.JLabel();
        btn_pesquisarFuncionario = new javax.swing.JButton();
        btn_listarClientes = new javax.swing.JButton();
        separador2 = new javax.swing.JSeparator();
        label_cliente = new javax.swing.JLabel();
        img_clientes = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        label_pedidos = new javax.swing.JLabel();
        img_agenda = new javax.swing.JLabel();
        btn_pedidosAberto = new javax.swing.JButton();
        img_ok = new javax.swing.JLabel();
        btn_designarFuncionario = new javax.swing.JButton();
        separador4 = new javax.swing.JSeparator();
        label_feedback = new javax.swing.JLabel();
        img_feedback = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        label_bemVindo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rp_logado = new javax.swing.JTextField();
        label_nome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seu_rp = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        background.setBackground(new java.awt.Color(30, 30, 30));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(1280, 720));
        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        background.setPreferredSize(new java.awt.Dimension(1280, 720));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_nomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        background.add(label_nomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 270, -1));

        img_cadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user.png"))); // NOI18N
        background.add(img_cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        btn_cadastrarFuncionario.setBackground(new java.awt.Color(14, 118, 196));
        btn_cadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarFuncionario.setText("Cadastrar funcionário");
        btn_cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarFuncionarioActionPerformed(evt);
            }
        });
        background.add(btn_cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));

        img_editarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/edit.png"))); // NOI18N
        background.add(img_editarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        btn_editarFuncionario.setBackground(new java.awt.Color(14, 118, 196));
        btn_editarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_editarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_editarFuncionario.setText("Editar funcionário");
        btn_editarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarFuncionarioActionPerformed(evt);
            }
        });
        background.add(btn_editarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, -1));

        separador.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 320, -1));

        label_funcionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_funcionario.setForeground(new java.awt.Color(255, 255, 255));
        label_funcionario.setText("Gerenciamento de funcionários");
        background.add(label_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        img_excluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/delet.png"))); // NOI18N
        background.add(img_excluirFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        btn_excluirFuncionario.setBackground(new java.awt.Color(14, 118, 196));
        btn_excluirFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_excluirFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluirFuncionario.setText("Excluir funcionário");
        btn_excluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirFuncionarioActionPerformed(evt);
            }
        });
        background.add(btn_excluirFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 202, -1));

        img_pesquisarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/search.png"))); // NOI18N
        background.add(img_pesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        btn_pesquisarFuncionario.setBackground(new java.awt.Color(14, 118, 196));
        btn_pesquisarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pesquisarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_pesquisarFuncionario.setText("Listar funcionários");
        btn_pesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarFuncionarioActionPerformed(evt);
            }
        });
        background.add(btn_pesquisarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 202, -1));

        btn_listarClientes.setBackground(new java.awt.Color(14, 118, 196));
        btn_listarClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_listarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_listarClientes.setText("Listar clientes");
        btn_listarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarClientesActionPerformed(evt);
            }
        });
        background.add(btn_listarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 200, -1));

        separador2.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 310, 10));

        label_cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_cliente.setForeground(new java.awt.Color(255, 255, 255));
        label_cliente.setText("Gerenciamento de clientes");
        background.add(label_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        img_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/client.png"))); // NOI18N
        background.add(img_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        separador3.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 310, 10));

        label_pedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        label_pedidos.setText("Pedidos em aberto");
        background.add(label_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        img_agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/calendar.png"))); // NOI18N
        background.add(img_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        btn_pedidosAberto.setBackground(new java.awt.Color(14, 118, 196));
        btn_pedidosAberto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pedidosAberto.setForeground(new java.awt.Color(255, 255, 255));
        btn_pedidosAberto.setText("Ver pedidos em aberto");
        btn_pedidosAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidosAbertoActionPerformed(evt);
            }
        });
        background.add(btn_pedidosAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 206, -1));

        img_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/ok.png"))); // NOI18N
        background.add(img_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        btn_designarFuncionario.setBackground(new java.awt.Color(14, 118, 196));
        btn_designarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_designarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_designarFuncionario.setText("Designar funcionários");
        btn_designarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_designarFuncionarioActionPerformed(evt);
            }
        });
        background.add(btn_designarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 200, -1));

        separador4.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 300, 10));

        label_feedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_feedback.setForeground(new java.awt.Color(255, 255, 255));
        label_feedback.setText("Feedbacks");
        background.add(label_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, -1, -1));

        img_feedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/feedback.png"))); // NOI18N
        background.add(img_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(14, 118, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver feedbacks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 200, -1));

        header.setBackground(new java.awt.Color(14, 118, 196));

        label_bemVindo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_bemVindo.setForeground(new java.awt.Color(255, 255, 255));
        label_bemVindo.setText("Bem vindo(a),");

        jButton2.setBackground(new java.awt.Color(14, 118, 196));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label_nome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_nome.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seu registro profissional é:");

        seu_rp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seu_rp.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(label_bemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nome))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seu_rp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 538, Short.MAX_VALUE)
                .addComponent(rp_logado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_bemVindo)
                            .addComponent(label_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(seu_rp)))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rp_logado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        footer.setBackground(new java.awt.Color(14, 118, 196));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Todos os direitos reservados a EletroTech Solutions");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CNPJ: 15.735.735/0001-30");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 721, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31))
        );

        background.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1280, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Serviços em andamento");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 300, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/voltage.png"))); // NOI18N
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, -1, -1));

        jButton3.setBackground(new java.awt.Color(14, 118, 196));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Serviços em andamento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarFuncionarioActionPerformed
        controller.mudaTelaInterna(new Listar_funcionarios());
    }//GEN-LAST:event_btn_pesquisarFuncionarioActionPerformed

    private void btn_cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarFuncionarioActionPerformed
        controller.mudaTelaInterna(new Cadastrar_funcionario());
    }//GEN-LAST:event_btn_cadastrarFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.mudaTelaInterna(new Feedbacks());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.mudaTela(new Login(), this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_editarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarFuncionarioActionPerformed
        controller.mudaTelaInterna(new Editar_funcionario());
    }//GEN-LAST:event_btn_editarFuncionarioActionPerformed

    private void btn_excluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirFuncionarioActionPerformed
        controller.mudaTelaInterna(new Excluir_funcionario());
    }//GEN-LAST:event_btn_excluirFuncionarioActionPerformed

    private void btn_listarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarClientesActionPerformed
        controller.mudaTelaInterna(new Listar_clientes());
    }//GEN-LAST:event_btn_listarClientesActionPerformed

    private void btn_pedidosAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidosAbertoActionPerformed
        controller.mudaTelaInterna(new Solicitacoes_abertas());
    }//GEN-LAST:event_btn_pedidosAbertoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controller.mudaTelaInterna(new Servicos_andamento());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_designarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_designarFuncionarioActionPerformed
        controller.mudaTelaInterna(new Designar_funcionario());
    }//GEN-LAST:event_btn_designarFuncionarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {

            int rp = Integer.parseInt(rp_logado.getText());

            for (Funcionario f : fdao.pesquisarFuncionario(rp)) {
                seu_rp.setText(String.valueOf(f.getRp()));
                label_nome.setText(f.getNome());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_cadastrarFuncionario;
    private javax.swing.JButton btn_designarFuncionario;
    private javax.swing.JButton btn_editarFuncionario;
    private javax.swing.JButton btn_excluirFuncionario;
    private javax.swing.JButton btn_listarClientes;
    private javax.swing.JButton btn_pedidosAberto;
    private javax.swing.JButton btn_pesquisarFuncionario;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel img_agenda;
    private javax.swing.JLabel img_cadastrarFuncionario;
    private javax.swing.JLabel img_clientes;
    private javax.swing.JLabel img_editarFuncionario;
    private javax.swing.JLabel img_excluirFuncionario;
    private javax.swing.JLabel img_feedback;
    private javax.swing.JLabel img_ok;
    private javax.swing.JLabel img_pesquisarFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_bemVindo;
    private javax.swing.JLabel label_cliente;
    private javax.swing.JLabel label_feedback;
    private javax.swing.JLabel label_funcionario;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_nomeUsuario;
    private javax.swing.JLabel label_pedidos;
    public javax.swing.JTextField rp_logado;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JLabel seu_rp;
    // End of variables declaration//GEN-END:variables
}
