/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import views.administrador.Home_adm;
import controller.PagesController;
import dao.FuncionarioDao;
import javax.swing.JOptionPane;
import model.Funcionario;
import views.funcionario.Home;

/**
 *
 * @author Aluno_Manha
 */
public class Login extends javax.swing.JFrame {

    public static Funcionario funcionario = new Funcionario();
    public static FuncionarioDao funcionariodao = new FuncionarioDao();

    PagesController controller = new PagesController();

    /**
     * Creates new form Login
     */
    public Login() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        eletrotech = new javax.swing.JLabel();
        label_rp = new javax.swing.JLabel();
        input_rp = new javax.swing.JTextField();
        label_senha = new javax.swing.JLabel();
        input_senha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        img_userLogin = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        background.setBackground(new java.awt.Color(30, 30, 30));
        background.setMaximumSize(new java.awt.Dimension(1280, 720));
        background.setMinimumSize(new java.awt.Dimension(1280, 720));
        background.setPreferredSize(new java.awt.Dimension(1280, 720));

        eletrotech.setBackground(new java.awt.Color(255, 255, 255));
        eletrotech.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        eletrotech.setForeground(new java.awt.Color(255, 255, 255));
        eletrotech.setText("Eletrotech");

        label_rp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_rp.setForeground(new java.awt.Color(255, 255, 255));
        label_rp.setText("Registro profissional");

        label_senha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_senha.setForeground(new java.awt.Color(255, 255, 255));
        label_senha.setText("Senha");

        btn_login.setBackground(new java.awt.Color(14, 118, 196));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Logar");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        img_userLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_login.png"))); // NOI18N

        jToggleButton1.setBackground(new java.awt.Color(14, 118, 196));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Sair");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(img_userLogin))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(btn_login))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_senha)
                            .addComponent(label_rp)
                            .addComponent(eletrotech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_rp)
                            .addComponent(input_senha))))
                .addContainerGap(526, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jToggleButton1)
                .addGap(114, 114, 114)
                .addComponent(img_userLogin)
                .addGap(18, 18, 18)
                .addComponent(eletrotech)
                .addGap(27, 27, 27)
                .addComponent(label_rp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_rp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_login)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        try {

            if (funcionariodao.checkLogin(Integer.parseInt(input_rp.getText()), String.valueOf(input_senha.getPassword()))) {
                JOptionPane.showMessageDialog(
                        null,
                        "Usuário logado com sucesso!",
                        "Login permitido",
                        JOptionPane.INFORMATION_MESSAGE);

                for (Funcionario f : funcionariodao.pesquisarFuncionario(Integer.parseInt(input_rp.getText()))) {
                    if (f.getAdmin() == 1) {
                        Home_adm homeadm = new Home_adm();
                        homeadm.show();
                        dispose();
                        
                        homeadm.rp_logado.setText(input_rp.getText());
                        
                    } else {
                        Home home_funcionario = new Home();
                        home_funcionario.show();
                        dispose();

                        home_funcionario.rp_logado.setText(input_rp.getText());
                    }
                }

            } else {

                JOptionPane.showMessageDialog(
                        null,
                        "Registro profissional e(ou) senhas estão incorretos",
                        "Login inválido",
                        JOptionPane.ERROR_MESSAGE);

                input_rp.setText("");
                input_senha.setText("");

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_loginActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel eletrotech;
    private javax.swing.JLabel img_userLogin;
    private javax.swing.JTextField input_rp;
    private javax.swing.JPasswordField input_senha;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label_rp;
    private javax.swing.JLabel label_senha;
    // End of variables declaration//GEN-END:variables
}
